// Minimal hello-world for the ovip_ace VIP (full ACE profile).
//
// !!  IMPORTANT  !!
// The ovip_ace VIP was generated by an AI (Claude) and has NOT been verified in
// simulation by a human. This example compiles; whether it runs to 0 errors is
// exactly the kind of bring-up work that still needs doing. See
// verif/ovip_ace/README.md and verif/ovip_ace/CONTRIBUTING.md.
//
// What this is meant to show:
//   - A master ACE agent + a slave/interconnect ACE agent on one interface.
//   - The master issues coherent writes (WriteUnique) then reads (ReadOnce),
//     carrying AxDOMAIN / AxSNOOP, backed by ovip_mem loopback on the slave.
//   - The interconnect side injects one ReadShared snoop; the master answers on
//     CR with the default "cache miss" response (CRRESP = 0, no data).
//   - RACK / WACK pulses are driven by the master and checked by both monitors.

`timescale 1ns/1ps

package coherent_loopback_pkg;
	import uvm_pkg::*;
	import ovip_global_pkg::*;
	import ovip_mem_pkg::*;
	import ovip_axi_pkg::*;
	import ovip_ace_pkg::*;
	`include "uvm_macros.svh"


	// Master sequence: 4 coherent writes, then 4 coherent reads at the same
	// addresses. Uses the ACE builders from ovip_ace_base_master_sequence.
	class coherent_master_seq extends ovip_ace_base_master_sequence;
		`uvm_object_utils(coherent_master_seq)
		`uvm_declare_p_sequencer(ovip_axi_base_sequencer)

		function new(string name = "coherent_master_seq");
			super.new(name);
		endfunction

		virtual task body();
			// Four WriteUnique (AWSNOOP=0b000 with a shareable domain), single
			// 4-byte beat each.
			for(int ii = 0; ii < 4; ii++) begin
				ovip_axi_data_t d[$] = '{32'hACE0_0000 + ii};
				ovip_axi_strb_t s[$] = '{8'h0F};
				ovip_ace_trans  tr;
				tr = make_write(ii*'h10, OVIP_ACE_AWSNOOP_WRITE_NO_SNOOP_OR_WRITE_UNIQUE,
				                OVIP_ACE_DOMAIN_INNER_SHAREABLE, d, s, OVIP_AXI_SIZE_4B);
				tr.id = ii;
				send(tr);
			end

			// Four ReadOnce (ARSNOOP=0b0000 with a shareable domain).
			for(int ii = 0; ii < 4; ii++) begin
				ovip_ace_trans tr;
				tr = make_read(ii*'h10, OVIP_ACE_ARSNOOP_READ_NO_SNOOP_OR_READ_ONCE,
				               OVIP_ACE_DOMAIN_INNER_SHAREABLE, OVIP_AXI_SIZE_4B, 0);
				tr.id = ii;
				send(tr);
			end

			wait_for_responses();
		endtask
	endclass


	class coherent_loopback_test extends uvm_test;
		`uvm_component_utils(coherent_loopback_test)

		ovip_ace_agent_config       master_cfg, slave_cfg;
		ovip_ace_agent              master_agent, slave_agent;
		ovip_mem                    mem;
		ovip_ace_base_slave_sequence slave_seq;

		function new(string name = "coherent_loopback_test", uvm_component parent = null);
			super.new(name, parent);
		endfunction

		function void build_phase(uvm_phase phase);
			super.build_phase(phase);

			mem = ovip_mem::type_id::create("mem", this);

			master_cfg = ovip_ace_agent_config::type_id::create("master_cfg");
			master_cfg.agent_type      = OVIP_MASTER_AGENT;
			master_cfg.profile         = OVIP_ACE_PROFILE_ACE;
			master_cfg.bus_width       = OVIP_AXI_BUS_WIDTH_8B;
			master_cfg.addr_width      = 32;
			master_cfg.cache_line_size = 64;
			master_cfg.acaddr_width    = 32;
			master_cfg.cddata_width    = 64; // matches the 8B (64-bit) bus / MAX_DATA_WIDTH
			master_cfg.is_active       = UVM_ACTIVE;

			slave_cfg = ovip_ace_agent_config::type_id::create("slave_cfg");
			slave_cfg.agent_type      = OVIP_SLAVE_AGENT;
			slave_cfg.profile         = OVIP_ACE_PROFILE_ACE;
			slave_cfg.bus_width       = OVIP_AXI_BUS_WIDTH_8B;
			slave_cfg.addr_width      = 32;
			slave_cfg.cache_line_size = 64;
			slave_cfg.acaddr_width    = 32;
			slave_cfg.cddata_width    = 64;
			slave_cfg.is_active       = UVM_ACTIVE;

			master_agent = ovip_ace_agent::type_id::create("master_agent", this);
			master_agent.cfg = master_cfg;
			slave_agent = ovip_ace_agent::type_id::create("slave_agent", this);
			slave_agent.cfg = slave_cfg;

			slave_seq = ovip_ace_base_slave_sequence::type_id::create("slave_seq");
			slave_seq.mem = mem;
		endfunction

		// Slave responder runs in the background for the whole run.
		virtual task run_phase(uvm_phase phase);
			super.run_phase(phase);
			fork
				slave_seq.start(slave_agent.sqr);
			join_none
		endtask

		virtual task reset_phase(uvm_phase phase);
			super.reset_phase(phase);
			phase.raise_objection(this);
			@(posedge master_agent.mon.vif.aresetn);
			phase.drop_objection(this);
		endtask

		virtual task main_phase(uvm_phase phase);
			coherent_master_seq   seq = coherent_master_seq::type_id::create("seq");
			ovip_ace_slave_driver slv_drv;
			super.main_phase(phase);
			phase.raise_objection(this);

			seq.start(master_agent.sqr);

			// Inject one snoop from the interconnect side: a ReadShared to the
			// address the master just touched. The master answers with the
			// default cache-miss response.
			if($cast(slv_drv, slave_agent.drv)) begin
				ovip_ace_trans snoop = ovip_ace_trans::type_id::create("snoop");
				snoop.direction    = OVIP_ACE_SNOOP;
				snoop.snoop_addr   = 'h10;
				snoop.acsnoop_code = OVIP_ACE_ACSNOOP_READ_SHARED;
				snoop.acprot       = 3'b000;
				slv_drv.push_snoop(snoop);
				// Give the snoop time to complete before ending the test.
				repeat(50) @(posedge master_agent.mon.vif.aclk);
			end

			phase.drop_objection(this);
		endtask
	endclass

endpackage : coherent_loopback_pkg


module tb_top;
import uvm_pkg::*;
import coherent_loopback_pkg::*;

logic clk = 0;
logic rst_n = 0;
always #500ps clk = ~clk;   // 1 GHz

// Master and interconnect/slave share a single ACE interface (no DUT between
// them -- the loopback runs entirely inside the VIP).
ovip_ace_agent_if ace_if(clk, rst_n);

// Dummy, unused AXI interface. ovip_ace is built on top of ovip_axi, so the
// AXI package (including its plain `virtual ovip_axi_agent_if` handles in the
// base agent/monitor/driver default specializations) is always elaborated.
// Questa (vsim-8451) needs at least one instance of that interface type to
// exist to resolve the virtual-interface type, even though this pure-ACE
// testbench never drives it. This single dead instance satisfies that.
ovip_axi_agent_if unused_axi_if(clk, rst_n);

initial begin
	uvm_config_db#(virtual ovip_ace_agent_if)::set(null, "*.master_agent*", "vif", ace_if);
	uvm_config_db#(virtual ovip_ace_agent_if)::set(null, "*.slave_agent*",  "vif", ace_if);
	run_test("coherent_loopback_test");
end

// Reset pulse: low for a few cycles, then high for the rest of the run.
initial begin
	repeat(2) @(posedge clk);
	rst_n = 1;
end
endmodule : tb_top
